package com.app.common.persistence;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import org.hibernate.annotations.IdGeneratorType;

/** Marks an identifier as generated by PostgreSQL {@code gen_random_uuid()}. */
@IdGeneratorType(PostgresUuidGenerator.class)
@Retention(RUNTIME)
@Target({FIELD, METHOD})
public @interface GeneratedPostgresUuid {}
