package com.app.modules.media.storage;

import java.net.URL;
import java.time.Instant;
import java.util.Map;

/** Service API for creating short-lived direct-upload URLs for object storage. */
public interface ObjectStoragePresignService {

    /**
     * Creates a pre-signed PUT URL for a single object key.
     *
     * @param storageKey object key generated by the backend
     * @param mimeType validated content type that the client must upload
     * @param fileSize validated content length in bytes
     * @return pre-signed upload details safe to return to the authenticated client
     */
    PresignedUpload presignPutObject(String storageKey, String mimeType, long fileSize);

    /** Value object containing upload URL details for the client. */
    record PresignedUpload(
            URL uploadUrl, String method, Map<String, String> requiredHeaders, Instant expiresAt) {}
}
