spring:
  config:
    import:
      - classpath:resilience/circuitbreaker/resilience4j-prod.yml
      - classpath:resilience/ratelimiter/resilience4j-prod.yml
      - classpath:resilience/retry/resilience4j-prod.yml

jpa:
  hibernate:
    ddl-auto: validate
  show-sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  mail:
    app-name: ${MAIL_APP_NAME}
    frontend-base-url: ${FRONTEND_BASE_URL}
  security:
    trusted-proxy-cidrs: []
    max-login-body-bytes: 2048