spring:
  application:
    name: app
  profiles:
    active: dev
  config:
    import:
      - optional:file:.env[.properties]
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    out-of-order: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}