spring:
  config:
    import:
      - classpath:resilience/circuitbreaker/resilience4j-dev.yml
      - classpath:resilience/ratelimiter/resilience4j-dev.yml
      - classpath:resilience/retry/resilience4j-dev.yml

jpa:
  hibernate:
    ddl-auto: validate
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      use_sql_comments: true

security:
  jwt:
    secret: ${JWT_SECRET}
    access-ttl: ${ACCESS_TOKEN_TTL}
    refresh-ttl: ${REFRESH_TOKEN_TTL}
    issuer: ${JWT_ISSUER}

app:
  base-url: ${APP_BASE_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  mail:
    from-address: ${MAIL_FROM_ADDRESS}
    from-name: ${MAIL_FROM_NAME}
    app-name: ${MAIL_APP_NAME}
    frontend-base-url: ${MAIL_FRONTEND_BASE_URL}

springdoc:
  swagger-ui:
    path: /vietrecruit/api-docs
    config-url: /vietrecruit/v3/api-docs/swagger-config
    url: /vietrecruit/v3/api-docs
  api-docs:
    path: /vietrecruit/v3/api-docs
  server-url: ${APP_BASE_URL}

