package com.app.modules.media.repository;

import com.app.modules.media.entity.MediaAsset;

/** Custom insert path that keeps the media asset UUID generated by PostgreSQL. */
public interface MediaAssetInsertRepository {

    MediaAsset insert(MediaAsset mediaAsset);
}
