-- ============================================================
-- PostgreSQL reference schema - GENERATED
-- ============================================================

-- Generated by `scripts/regenerate_schema_sql.sh` from a `pg_dump --schema-only` of a
-- clean database with Flyway migrations V01 to V111 applied; it is a reference
-- rendering of the final-state schema and is never applied by Flyway.
--
-- Do not hand-edit the structure. Correct a migration and regenerate.
-- Explanatory comments are carried forward from the previous revision of this file and
-- are the one part a person maintains by hand.
--
-- `flyway_schema_history` and the dated `user_events_YYYY_MM` partitions are omitted:
-- the first is Flyway's own bookkeeping and the others are created at runtime by
-- `UserEventsPartitionJob`, so neither is schema a reader should treat as declared.

-- ============================================================
-- EXTENSIONS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS btree_gin WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE admin_action_type AS ENUM (
    'ban_user',
    'unban_user',
    'suspend_user',
    'unsuspend_user',
    'remove_post',
    'restore_post',
    'remove_comment',
    'restore_comment',
    'resolve_report',
    'dismiss_report',
    'change_user_role',
    'warn_user',
    'revoke_warning',
    'issue_strike',
    'revoke_strike',
    'escalate_report',
    'force_logout',
    'create_hashtag',
    'edit_hashtag',
    'ban_hashtag',
    'unban_hashtag',
    'delete_hashtag',
    'remove_story',
    'restore_story',
    'remove_message',
    'restore_message',
    'revoke_session',
    'pin_hashtag',
    'unpin_hashtag',
    'respond_support_ticket',
    'reject_support_ticket',
    'escalate_support_ticket',
    'send_mail_campaign',
    'grant_verification',
    'reject_verification',
    'revoke_verification'
);
CREATE TYPE email_delivery_status AS ENUM (
    'pending',
    'sent',
    'failed',
    'throttled',
    'skipped'
);
CREATE TYPE event_type AS ENUM (
    'post_view',
    'post_like',
    'post_unlike',
    'post_save',
    'post_unsave',
    'post_share',
    'post_comment',
    'story_view',
    'story_reply',
    'profile_view',
    'profile_follow',
    'profile_unfollow',
    'search',
    'hashtag_click',
    'comment_like',
    'comment_reply',
    'message_send',
    'session_start',
    'session_end',
    'app_open'
);
CREATE TYPE follow_status AS ENUM (
    'pending',
    'accepted'
);
CREATE TYPE hashtag_status AS ENUM (
    'active',
    'banned',
    'deleted'
);
CREATE TYPE mail_campaign_recipient_status AS ENUM (
    'pending',
    'queued',
    'skipped_opted_out',
    'failed',
    'skipped_not_allowed'
);
CREATE TYPE mail_campaign_status AS ENUM (
    'draft',
    'scheduled',
    'sending',
    'sent',
    'cancelled',
    'failed'
);
CREATE TYPE media_type AS ENUM (
    'image',
    'video'
);
CREATE TYPE message_type AS ENUM (
    'text',
    'image',
    'video',
    'post_share',
    'story_share'
);
CREATE TYPE notification_type AS ENUM (
    'like_post',
    'like_comment',
    'comment_post',
    'reply_comment',
    'follow',
    'follow_request',
    'mention_post',
    'mention_comment',
    'story_view',
    'message',
    'warning',
    'post_removed',
    'report_post_removed',
    'post_restored',
    'report_dismissed',
    'support_ticket_update'
);
CREATE TYPE oauth_provider AS ENUM (
    'google',
    'facebook',
    'apple'
);
CREATE TYPE post_status AS ENUM (
    'draft',
    'published',
    'archived',
    'removed'
);
CREATE TYPE post_type AS ENUM (
    'image',
    'video',
    'carousel',
    'text'
);
CREATE TYPE report_reason AS ENUM (
    'spam',
    'nudity',
    'violence',
    'hate_speech',
    'harassment',
    'false_information',
    'scam',
    'other'
);
CREATE TYPE report_status AS ENUM (
    'pending',
    'reviewing',
    'resolved',
    'dismissed',
    'escalated'
);
CREATE TYPE report_type AS ENUM (
    'post',
    'comment',
    'user',
    'story',
    'message'
);
CREATE TYPE stat_granularity AS ENUM (
    'half_hour',
    'day'
);
CREATE TYPE story_type AS ENUM (
    'image',
    'video'
);
CREATE TYPE support_category AS ENUM (
    'appeal_ban',
    'appeal_suspension',
    'appeal_warning_strike',
    'appeal_content_removal',
    'account_access',
    'account_data',
    'bug_report',
    'safety_concern',
    'other',
    'verification_request'
);
CREATE TYPE support_source AS ENUM (
    'authenticated',
    'signed_link',
    'public_form'
);
CREATE TYPE support_ticket_status AS ENUM (
    'pending_confirmation',
    'open',
    'in_progress',
    'escalated',
    'answered',
    'rejected'
);
CREATE TYPE user_role AS ENUM (
    'user',
    'moderator',
    'admin'
);
CREATE TYPE user_status AS ENUM (
    'active',
    'suspended',
    'deactivated',
    'banned'
);
CREATE TYPE verification_revocation_actor AS ENUM (
    'moderator',
    'system'
);

-- ============================================================
-- MODULE: AUTH
-- ============================================================

-- Core user entity
CREATE TABLE users (
    id                UUID         NOT NULL DEFAULT gen_random_uuid(),
    username          VARCHAR(30)  NOT NULL,
    email             VARCHAR(255) NOT NULL,
    display_name      VARCHAR(100),
    bio               TEXT,
    avatar_url        TEXT,
    website_url       TEXT,
    role              user_role    NOT NULL DEFAULT 'user',
    status            user_status  NOT NULL DEFAULT 'active',
    is_private        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_verified       BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Denormalized counters (maintained by triggers)
    follower_count    INTEGER      NOT NULL DEFAULT 0,
    following_count   INTEGER      NOT NULL DEFAULT 0,
    post_count        INTEGER      NOT NULL DEFAULT 0,
    -- Timestamps
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ,
    banner_url        TEXT,
    -- Administrative visibility (V56). Written through IpExtractor, which honours
    -- X-Forwarded-For only from a configured trusted proxy.
    registration_ip   INET,
    last_login_ip     INET,
    -- Advances on a real login only, never on a token refresh
    last_login_at     TIMESTAMPTZ,
    -- Meaningful only while status = 'suspended'; NULL means indefinite
    suspended_until   TIMESTAMPTZ,
    -- Stamped into every access token at issuance and compared on every authenticated request
    -- (V58). Advancing it invalidates every token already issued to the account. Written only by
    -- the atomic increment in AdminUserRepository, never through the User entity.
    token_epoch       INTEGER      NOT NULL DEFAULT 0,
    verified_category VARCHAR(50),
    CONSTRAINT users_follower_count_check CHECK ((follower_count >= 0)),
    CONSTRAINT users_following_count_check CHECK ((following_count >= 0)),
    CONSTRAINT users_post_count_check CHECK ((post_count >= 0)),
    PRIMARY KEY (id),
    UNIQUE (email),
    UNIQUE (username)
);

-- Local credentials (email + password login)
-- password_hash is nullable to support OAuth-only users who have no local password
CREATE TABLE user_credentials (
    user_id           UUID        NOT NULL,
    password_hash     TEXT,
    email_verified    BOOLEAN     NOT NULL DEFAULT FALSE,
    email_verified_at TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- OAuth provider accounts (Google, etc.)
-- Note: access_token, refresh_token, token_expires_at were dropped in V23 (drop_legacy_plaintext_credential_columns).
-- These columns will be re-added with encrypted storage when that feature is implemented.
CREATE TABLE oauth_accounts (
    id             UUID           NOT NULL DEFAULT gen_random_uuid(),
    user_id        UUID           NOT NULL,
    provider       oauth_provider NOT NULL,
    provider_id    VARCHAR(255)   NOT NULL,
    provider_email VARCHAR(255),
    created_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (provider, provider_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- JWT refresh tokens (stored as hash for security)
CREATE TABLE refresh_tokens (
    id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    user_id    UUID         NOT NULL,
    token_hash TEXT         NOT NULL,
    device_id  VARCHAR(255),
    user_agent TEXT,
    ip_address INET,
    expires_at TIMESTAMPTZ  NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (token_hash),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: USER PROFILE & SETTINGS
-- ============================================================

-- Per-user notification and privacy settings
CREATE TABLE user_settings (
    user_id                UUID        NOT NULL,
    -- Notification toggles
    notify_likes           BOOLEAN     NOT NULL DEFAULT TRUE,
    notify_comments        BOOLEAN     NOT NULL DEFAULT TRUE,
    notify_follows         BOOLEAN     NOT NULL DEFAULT TRUE,
    notify_mentions        BOOLEAN     NOT NULL DEFAULT TRUE,
    notify_messages        BOOLEAN     NOT NULL DEFAULT TRUE,
    -- Privacy
    show_activity_status   BOOLEAN     NOT NULL DEFAULT TRUE,
    allow_story_replies    BOOLEAN     NOT NULL DEFAULT TRUE,
    allow_message_requests BOOLEAN     NOT NULL DEFAULT TRUE,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    email_opt_out          BOOLEAN     NOT NULL DEFAULT FALSE,
    unsubscribe_token      VARCHAR(64),
    suggestible            BOOLEAN     NOT NULL DEFAULT TRUE,
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Device push notification tokens
CREATE TABLE push_tokens (
    id           UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id      UUID        NOT NULL,
    token        TEXT        NOT NULL,
    platform     VARCHAR(10) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    CONSTRAINT push_tokens_platform_check CHECK (((platform)::TEXT = ANY ((ARRAY['ios'::VARCHAR, 'android'::VARCHAR, 'web'::VARCHAR])::TEXT[]))),
    PRIMARY KEY (id),
    UNIQUE (token),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: SOCIAL GRAPH (Follow / Block)
-- ============================================================

-- Follow relationships (unidirectional, like Instagram)
CREATE TABLE follows (
    follower_id  UUID          NOT NULL,
    following_id UUID          NOT NULL,
    status       follow_status NOT NULL DEFAULT 'accepted',
    -- status = 'pending' when target account is private
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT follows_check CHECK ((follower_id <> following_id)),
    PRIMARY KEY (follower_id, following_id),
    FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Block relationships
CREATE TABLE blocks (
    blocker_id UUID        NOT NULL,
    blocked_id UUID        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT blocks_check CHECK ((blocker_id <> blocked_id)),
    PRIMARY KEY (blocker_id, blocked_id),
    FOREIGN KEY (blocked_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (blocker_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: MEDIA ASSETS (Cloudflare R2)
-- ============================================================

-- Decision: store full metadata (width, height, duration, blurhash)
-- Reasons:
--   1. Aspect ratio needed for responsive UI layout (no extra API call)
--   2. Video duration required for player rendering
--   3. Blurhash provides loading placeholder (same as Instagram)
--   4. Avoids repeated HEAD requests to CDN per render
CREATE TABLE media_assets (
    id          UUID         NOT NULL DEFAULT gen_random_uuid(),
    user_id     UUID         NOT NULL,
    storage_key TEXT         NOT NULL,
    cdn_url     TEXT         NOT NULL,
    media_type  media_type   NOT NULL,
    mime_type   VARCHAR(100) NOT NULL,
    file_size   BIGINT       NOT NULL,
    width       INTEGER,
    height      INTEGER,
    duration    INTEGER,
    blurhash    VARCHAR(100),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT media_assets_duration_check CHECK ((duration >= 0)),
    CONSTRAINT media_assets_file_size_check CHECK ((file_size > 0)),
    CONSTRAINT media_assets_height_check CHECK ((height > 0)),
    CONSTRAINT media_assets_width_check CHECK ((width > 0)),
    PRIMARY KEY (id),
    UNIQUE (storage_key),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: POST
-- ============================================================

CREATE TABLE posts (
    id                       UUID          NOT NULL DEFAULT gen_random_uuid(),
    user_id                  UUID          NOT NULL,
    caption                  TEXT,
    post_type                post_type     NOT NULL DEFAULT 'image',
    status                   post_status   NOT NULL DEFAULT 'published',
    -- Denormalized counters for read performance
    like_count               INTEGER       NOT NULL DEFAULT 0,
    comment_count            INTEGER       NOT NULL DEFAULT 0,
    save_count               INTEGER       NOT NULL DEFAULT 0,
    view_count               INTEGER       NOT NULL DEFAULT 0,
    -- Optional location metadata
    location_name            VARCHAR(255),
    latitude                 NUMERIC(10,8),
    longitude                NUMERIC(11,8),
    -- Timestamps
    created_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted_at               TIMESTAMPTZ,
    -- Status held before a moderation removal, so restore returns the post there instead of
    -- publishing it (V59). Non-null only while the post sits removed by moderation.
    status_before_moderation post_status,
    CONSTRAINT posts_comment_count_check CHECK ((comment_count >= 0)),
    CONSTRAINT posts_like_count_check CHECK ((like_count >= 0)),
    CONSTRAINT posts_save_count_check CHECK ((save_count >= 0)),
    CONSTRAINT posts_view_count_check CHECK ((view_count >= 0)),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Post media items (supports carousel: multiple images/videos)
CREATE TABLE post_media (
    id             UUID        NOT NULL DEFAULT gen_random_uuid(),
    post_id        UUID        NOT NULL,
    media_asset_id UUID        NOT NULL,
    "position" SMALLINT DEFAULT 0 NOT NULL,
    alt_text       TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (post_id, "position"),
    FOREIGN KEY (media_asset_id) REFERENCES media_assets(id),
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- Post likes (compound PK = one like per user per post)
CREATE TABLE post_likes (
    user_id    UUID        NOT NULL,
    post_id    UUID        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, post_id),
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Post saves / bookmarks
CREATE TABLE post_saves (
    user_id    UUID        NOT NULL,
    post_id    UUID        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, post_id),
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Post caption edit history (append-only audit; rows are never updated or soft-deleted)
CREATE TABLE post_edit_history (
    id               UUID        NOT NULL DEFAULT gen_random_uuid(),
    post_id          UUID        NOT NULL,
    editor_id        UUID        NOT NULL,
    previous_caption TEXT,
    edited_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (editor_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: COMMENTS (Nested, Adjacency List + root_id + depth)
-- ============================================================

-- Design: Adjacency list with root_id + depth columns.
-- Strategy:
--   - parent_id  → immediate parent (standard adjacency list)
--   - root_id    → top-level comment ancestor (null if top-level)
--   - depth      → nesting level (0 = top-level, 1 = direct reply, ...)
--   - Depth capped at 10 to prevent runaway nesting.
--   - Retrieval of subtrees uses WITH RECURSIVE CTE (built into PostgreSQL).
--   - This is simpler than Closure Table while remaining maintainable
--     for a student team; sufficient for Instagram-style 2-level display.
CREATE TABLE comments (
    id                UUID        NOT NULL DEFAULT gen_random_uuid(),
    post_id           UUID        NOT NULL,
    user_id           UUID        NOT NULL,
    parent_id         UUID,
    root_id           UUID,
    depth             SMALLINT    NOT NULL DEFAULT 0,
    content           TEXT        NOT NULL,
    -- Denormalized counters
    like_count        INTEGER     NOT NULL DEFAULT 0,
    reply_count       INTEGER     NOT NULL DEFAULT 0,
    -- Timestamps
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ,
    moderation_status VARCHAR(20) NOT NULL DEFAULT 'approved'::VARCHAR,
    -- Set by application code on a content edit only; NULL means never edited. Distinct from
    -- updated_at, which the row-level trigger moves whenever a counter changes.
    edited_at         TIMESTAMPTZ,
    admin_removed_at  TIMESTAMPTZ,
    CONSTRAINT comments_depth_check CHECK (((depth >= 0) AND (depth <= 10))),
    CONSTRAINT comments_like_count_check CHECK ((like_count >= 0)),
    CONSTRAINT comments_reply_count_check CHECK ((reply_count >= 0)),
    PRIMARY KEY (id),
    FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (root_id) REFERENCES comments(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Comment likes
CREATE TABLE comment_likes (
    user_id    UUID        NOT NULL,
    comment_id UUID        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, comment_id),
    FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Comment write idempotency: caches the first response per (user_id, idempotency_key).
CREATE TABLE comment_write_idempotency (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    request_hash    VARCHAR(64) NOT NULL,
    response_body   JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (user_id, idempotency_key),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: HASHTAG & TRENDING
-- ============================================================

CREATE TABLE hashtags (
    id          UUID           NOT NULL DEFAULT gen_random_uuid(),
    name        VARCHAR(100)   NOT NULL,
    post_count  INTEGER        NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    -- 'deleted' is a state, never a row removal: deleting the row cascades to post_hashtags and
    -- drives the post_count trigger over every post that used the tag.
    status      hashtag_status NOT NULL DEFAULT 'active',
    status_note TEXT,
    status_at   TIMESTAMPTZ,
    status_by   UUID,
    pinned_at   TIMESTAMPTZ,
    pinned_by   UUID,
    CONSTRAINT hashtags_pin_pair CHECK ((((pinned_at IS NULL) AND (pinned_by IS NULL)) OR (pinned_at IS NOT NULL))),
    CONSTRAINT hashtags_post_count_check CHECK ((post_count >= 0)),
    PRIMARY KEY (id),
    UNIQUE (name),
    FOREIGN KEY (pinned_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (status_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE post_hashtags (
    post_id    UUID        NOT NULL,
    hashtag_id UUID        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (post_id, hashtag_id),
    FOREIGN KEY (hashtag_id) REFERENCES hashtags(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- Trending snapshots: populated by a scheduled background job
CREATE TABLE hashtag_trending (
    hashtag_id   UUID        NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end   TIMESTAMPTZ NOT NULL,
    post_count   INTEGER     NOT NULL DEFAULT 0,
    rank         INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (hashtag_id, period_start),
    FOREIGN KEY (hashtag_id) REFERENCES hashtags(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: STORY (24-hour Ephemeral)
-- ============================================================

CREATE TABLE stories (
    id               UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id          UUID        NOT NULL,
    media_asset_id   UUID        NOT NULL,
    story_type       story_type  NOT NULL DEFAULT 'image',
    caption          TEXT,
    view_count       INTEGER     NOT NULL DEFAULT 0,
    expires_at       TIMESTAMPTZ NOT NULL DEFAULT (NOW() + '24:00:00'::INTERVAL),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ,
    like_count       INTEGER     NOT NULL DEFAULT 0,
    admin_removed_at TIMESTAMPTZ,
    CONSTRAINT stories_like_count_check CHECK ((like_count >= 0)),
    CONSTRAINT stories_view_count_check CHECK ((view_count >= 0)),
    PRIMARY KEY (id),
    FOREIGN KEY (media_asset_id) REFERENCES media_assets(id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE story_views (
    story_id  UUID        NOT NULL,
    viewer_id UUID        NOT NULL,
    viewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (story_id, viewer_id),
    FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE,
    FOREIGN KEY (viewer_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Story views (deduplicated per viewer)
-- Story likes, mirroring post_likes: composite primary key, and a counter on the parent row kept
-- by a trigger rather than by application code (V49).
CREATE TABLE story_likes (
    user_id    UUID        NOT NULL,
    story_id   UUID        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, story_id),
    FOREIGN KEY (story_id) REFERENCES stories(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: NOTIFICATIONS
-- ============================================================

CREATE TABLE notifications (
    id           UUID              NOT NULL DEFAULT gen_random_uuid(),
    recipient_id UUID              NOT NULL,
    actor_id     UUID,
    type         notification_type NOT NULL,
    -- Polymorphic target entity
    entity_type  VARCHAR(50),
    entity_id    UUID,
    is_read      BOOLEAN           NOT NULL DEFAULT FALSE,
    read_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
    -- Denormalised so a notification can deep-link to the post without the client resolving
    -- entity_id first; null for a notification with no post (V47).
    post_id      UUID,
    message      TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: DIRECT MESSAGE / CHAT
-- ============================================================

-- Every conversation is 1-1; group conversations were removed (see
-- archived_group_conversations below). direct_pair_key is the two participants' user_id values
-- in sorted order, enforced unique so a pair can never hold two separate threads.
CREATE TABLE conversations (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    created_by      UUID,
    last_message_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    direct_pair_key TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

-- Members of a conversation
CREATE TABLE conversation_participants (
    conversation_id    UUID        NOT NULL,
    user_id            UUID        NOT NULL,
    joined_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    left_at            TIMESTAMPTZ,
    last_read_at       TIMESTAMPTZ,
    pinned_at          TIMESTAMPTZ,
    is_muted           BOOLEAN     NOT NULL DEFAULT FALSE,
    nickname           VARCHAR(50),
    is_manually_unread BOOLEAN     NOT NULL DEFAULT FALSE,
    PRIMARY KEY (conversation_id, user_id),
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Individual messages
CREATE TABLE messages (
    id               UUID         NOT NULL DEFAULT gen_random_uuid(),
    conversation_id  UUID         NOT NULL,
    sender_id        UUID,
    message_type     message_type NOT NULL DEFAULT 'text',
    content          TEXT,
    media_asset_id   UUID,
    -- Shared content references
    shared_post_id   UUID,
    shared_story_id  UUID,
    -- Thread reply
    reply_to_id      UUID,
    -- Sender-owned tombstone. Set together on the sender's own delete, which also clears content,
    -- so a sender deletion is irreversible by design.
    is_deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    -- Moderation-owned tombstone, independent of the pair above. Administrative removal sets it
    -- and preserves content so a restore can return the message; clearing it never undoes a
    -- sender deletion. A message is hidden when either tombstone is set.
    admin_removed_at TIMESTAMPTZ,
    PRIMARY KEY (id),
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    FOREIGN KEY (media_asset_id) REFERENCES media_assets(id),
    FOREIGN KEY (reply_to_id) REFERENCES messages(id) ON DELETE SET NULL,
    FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (shared_post_id) REFERENCES posts(id) ON DELETE SET NULL,
    FOREIGN KEY (shared_story_id) REFERENCES stories(id) ON DELETE SET NULL
);

-- Write idempotency for message sends (V31). A retried send carrying the same key returns the
-- stored response rather than creating a second message; request_hash catches a key reused for a
-- different request.
CREATE TABLE message_write_idempotency (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    request_hash    VARCHAR(64) NOT NULL,
    response_body   JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (user_id, idempotency_key),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Snapshot of every group conversation, its members, and its messages, taken before group chat
-- was removed as a product decision. No foreign keys back into the live schema: these rows must
-- outlive the conversations they describe.
CREATE TABLE archived_group_conversations (
    id               UUID         NOT NULL,
    group_name       VARCHAR(100),
    group_avatar_url TEXT,
    created_by       UUID,
    last_message_at  TIMESTAMPTZ,
    created_at       TIMESTAMPTZ,
    archived_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE archived_group_participants (
    conversation_id UUID        NOT NULL,
    user_id         UUID        NOT NULL,
    is_admin        BOOLEAN,
    joined_at       TIMESTAMPTZ,
    left_at         TIMESTAMPTZ,
    last_read_at    TIMESTAMPTZ,
    archived_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE archived_group_messages (
    id              UUID        NOT NULL,
    conversation_id UUID        NOT NULL,
    sender_id       UUID,
    message_type    TEXT,
    content         TEXT,
    media_asset_id  UUID,
    shared_post_id  UUID,
    shared_story_id UUID,
    reply_to_id     UUID,
    is_deleted      BOOLEAN,
    created_at      TIMESTAMPTZ,
    archived_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
);

-- ============================================================
-- MODULE: REPORT (Content Flagging)
-- ============================================================

CREATE TABLE reports (
    id                UUID          NOT NULL DEFAULT gen_random_uuid(),
    reporter_id       UUID          NOT NULL,
    report_type       report_type   NOT NULL,
    report_reason     report_reason NOT NULL,
    entity_id         UUID          NOT NULL,
    description       TEXT,
    status            report_status NOT NULL DEFAULT 'pending',
    reviewed_by       UUID,
    reviewed_at       TIMESTAMPTZ,
    resolution_note   TEXT,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    -- Escalation to an administrator (V65). Columns rather than a join to admin_actions, so
    -- the queue read that shows the reason does not depend on the audit log.
    escalated_by      UUID,
    escalated_at      TIMESTAMPTZ,
    escalation_reason TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (escalated_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);

-- ============================================================
-- MODULE: METADATA CONFIG
-- ============================================================

-- System-wide configurable limits and TTL values
CREATE TABLE system_settings (
    key         VARCHAR(100) NOT NULL,
    value       TEXT         NOT NULL,
    description TEXT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (key)
);

-- Registry of notification types with display and toggle settings
-- type_key maps to values in the notification_type enum
CREATE TABLE notification_type_configs (
    type_key           VARCHAR(100) NOT NULL,
    display_name       VARCHAR(100) NOT NULL,
    template_key       VARCHAR(100),
    is_user_toggleable BOOLEAN      NOT NULL DEFAULT TRUE,
    is_enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (type_key)
);

-- Display metadata and policy configuration for each report reason
-- reason_key maps to values in the report_reason enum
-- applies_to: empty array means applies to all report types
CREATE TABLE report_reason_configs (
    reason_key   VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    description  TEXT,
    applies_to VARCHAR(50)[] DEFAULT '{}'::VARCHAR[] NOT NULL,
    is_enabled   BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order   SMALLINT     NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (reason_key)
);

-- Registry of admin moderation actions with behavioral flags
-- action_key maps to values in the admin_action_type enum
CREATE TABLE moderation_action_configs (
    action_key      VARCHAR(100) NOT NULL,
    display_name    VARCHAR(100) NOT NULL,
    requires_reason BOOLEAN      NOT NULL DEFAULT FALSE,
    is_reversible   BOOLEAN      NOT NULL DEFAULT TRUE,
    is_enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (action_key)
);

-- Feature enable/disable control with optional environment scoping
CREATE TABLE feature_flags (
    flag_key    VARCHAR(100) NOT NULL,
    is_enabled  BOOLEAN      NOT NULL DEFAULT FALSE,
    description TEXT,
    environment VARCHAR(20)  NOT NULL DEFAULT 'all'::VARCHAR,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT feature_flags_environment_check CHECK (((environment)::TEXT = ANY ((ARRAY['all'::VARCHAR, 'dev'::VARCHAR, 'staging'::VARCHAR, 'prod'::VARCHAR])::TEXT[]))),
    PRIMARY KEY (flag_key)
);

CREATE TABLE support_category_configs (
    category_key       VARCHAR(100) NOT NULL,
    display_name       VARCHAR(100) NOT NULL,
    description        TEXT,
    is_appeal          BOOLEAN      NOT NULL DEFAULT FALSE,
    allows_public_form BOOLEAN      NOT NULL DEFAULT TRUE,
    is_enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order         SMALLINT     NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (category_key)
);

CREATE TABLE verification_categories (
    category_key VARCHAR(50)  NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    covers       TEXT         NOT NULL,
    icon_key     VARCHAR(50)  NOT NULL,
    is_enabled   BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order   SMALLINT     NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (category_key)
);

-- ============================================================
-- MODULE: ADMIN (Moderation Audit Log)
-- ============================================================

CREATE TABLE admin_actions (
    id                 UUID              NOT NULL DEFAULT gen_random_uuid(),
    admin_id           UUID,
    action_type        admin_action_type NOT NULL,
    target_user_id     UUID,
    target_entity_type VARCHAR(50),
    target_entity_id   UUID,
    report_id          UUID,
    reason             TEXT,
    metadata           JSONB,
    created_at         TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE SET NULL,
    FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Warnings a moderator issues against an account. Three active warnings produce a strike.
-- admin_action_id is NOT NULL: every row here is explained by an audit row written in the same
-- transaction, and the foreign key is what makes that impossible to skip.
-- reason_key references report_reason_configs, which is that table's only runtime reader.
CREATE TABLE user_warnings (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL,
    issued_by       UUID,
    reason_key      VARCHAR(50) NOT NULL,
    note            TEXT        NOT NULL,
    admin_action_id UUID        NOT NULL,
    revoked_at      TIMESTAMPTZ,
    revoked_by      UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT user_warnings_note_not_blank CHECK ((length(btrim(note)) > 0)),
    PRIMARY KEY (id),
    FOREIGN KEY (admin_action_id) REFERENCES admin_actions(id),
    FOREIGN KEY (issued_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (reason_key) REFERENCES report_reason_configs(reason_key),
    FOREIGN KEY (revoked_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Strikes, the consequence three active warnings produce.
-- strike_number is CHECK (>= 1), deliberately not capped at 3: an administrator may unban a
-- strike-3 account by hand, and a cap would make that account's next strike fail to insert.
-- Strike 3 and every strike above it carry the same consequence, so a cap would buy nothing.
CREATE TABLE user_strikes (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL,
    strike_number   SMALLINT    NOT NULL,
    triggered_by    UUID,
    admin_action_id UUID        NOT NULL,
    revoked_at      TIMESTAMPTZ,
    revoked_by      UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT user_strikes_strike_number_check CHECK ((strike_number >= 1)),
    PRIMARY KEY (id),
    FOREIGN KEY (admin_action_id) REFERENCES admin_actions(id),
    FOREIGN KEY (revoked_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (triggered_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Pre-aggregated platform statistics (V70).
-- Written only by the collection and roll-up jobs, never from a request path. A gauge is an
-- absolute snapshot bounded by the end of its bucket; a flow is a direct count over the bucket
-- window and is never derived by subtracting consecutive gauges. GROUP BY produces no row for an
-- empty group, so a dimension nobody holds in a bucket has no row rather than a row holding zero,
-- and every reader treats a missing dimension as zero. The composite primary key with
-- ON CONFLICT DO UPDATE is what keeps a double run harmless rather than duplicative.
CREATE TABLE platform_stats (
    bucket_start TIMESTAMPTZ      NOT NULL,
    granularity  stat_granularity NOT NULL,
    metric_key   VARCHAR(64)      NOT NULL,
    dimension    VARCHAR(64)      NOT NULL DEFAULT ''::VARCHAR,
    value        BIGINT           NOT NULL,
    computed_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    PRIMARY KEY (bucket_start, granularity, metric_key, dimension)
);

-- ============================================================
-- MODULE: SUPPORT (Tickets, Appeals, Verification)
-- ============================================================

CREATE TABLE support_tickets (
    id                UUID                  NOT NULL DEFAULT gen_random_uuid(),
    user_id           UUID,
    contact_email     VARCHAR(255)          NOT NULL,
    category          support_category      NOT NULL,
    subject           VARCHAR(200)          NOT NULL,
    body              TEXT                  NOT NULL,
    status            support_ticket_status NOT NULL DEFAULT 'open',
    source            support_source        NOT NULL,
    admin_action_id   UUID,
    assigned_to       UUID,
    assigned_at       TIMESTAMPTZ,
    staff_response    TEXT,
    internal_note     TEXT,
    responded_by      UUID,
    responded_at      TIMESTAMPTZ,
    escalated_by      UUID,
    escalated_at      TIMESTAMPTZ,
    escalation_reason TEXT,
    created_at        TIMESTAMPTZ           NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ           NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (admin_action_id) REFERENCES admin_actions(id) ON DELETE SET NULL,
    FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (escalated_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (responded_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE user_verifications (
    id                UUID                          NOT NULL DEFAULT gen_random_uuid(),
    user_id           UUID                          NOT NULL,
    category_key      VARCHAR(50)                   NOT NULL,
    request_ticket_id UUID,
    granted_by        UUID,
    granted_at        TIMESTAMPTZ                   NOT NULL DEFAULT NOW(),
    granted_action_id UUID,
    revoked_at        TIMESTAMPTZ,
    revoked_by        UUID,
    revocation_reason TEXT,
    revocation_actor  verification_revocation_actor,
    revoked_action_id UUID,
    CONSTRAINT user_verifications_revocation_pair CHECK ((((revoked_at IS NULL) AND (revocation_actor IS NULL) AND (revoked_by IS NULL) AND (revocation_reason IS NULL) AND (revoked_action_id IS NULL)) OR ((revoked_at IS NOT NULL) AND (revocation_actor IS NOT NULL)))),
    CONSTRAINT user_verifications_system_has_no_actor CHECK (((revocation_actor IS DISTINCT FROM 'system'::verification_revocation_actor) OR (revoked_by IS NULL))),
    PRIMARY KEY (id),
    FOREIGN KEY (category_key) REFERENCES verification_categories(category_key),
    FOREIGN KEY (granted_action_id) REFERENCES admin_actions(id) ON DELETE SET NULL,
    FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (request_ticket_id) REFERENCES support_tickets(id) ON DELETE SET NULL,
    FOREIGN KEY (revoked_action_id) REFERENCES admin_actions(id) ON DELETE SET NULL,
    FOREIGN KEY (revoked_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE verification_requests (
    ticket_id                 UUID         NOT NULL,
    user_id                   UUID         NOT NULL,
    category_key              VARCHAR(50)  NOT NULL,
    claimed_name              VARCHAR(100) NOT NULL,
    evidence_website          TEXT,
    evidence_other_profile    TEXT,
    evidence_email_domain     TEXT,
    evidence_published_work   TEXT,
    evidence_press            TEXT,
    evidence_official_listing TEXT,
    evidence_note             TEXT,
    evidence_field_count      SMALLINT     NOT NULL,
    created_at                TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT verification_requests_evidence_count_bound CHECK ((evidence_field_count <= 7)),
    CONSTRAINT verification_requests_min_evidence CHECK ((evidence_field_count >= 3)),
    PRIMARY KEY (ticket_id),
    FOREIGN KEY (category_key) REFERENCES verification_categories(category_key),
    FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: MAIL
-- ============================================================

CREATE TABLE email_deliveries (
    id                  UUID                  NOT NULL DEFAULT gen_random_uuid(),
    recipient_user_id   UUID,
    recipient_email     VARCHAR(255)          NOT NULL,
    template_key        VARCHAR(100)          NOT NULL,
    admin_action_id     UUID,
    status              email_delivery_status NOT NULL DEFAULT 'pending',
    provider_message_id VARCHAR(255),
    error_text          TEXT,
    attempt_count       INTEGER               NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ           NOT NULL DEFAULT NOW(),
    sent_at             TIMESTAMPTZ,
    CONSTRAINT email_deliveries_attempt_count_check CHECK ((attempt_count >= 0)),
    PRIMARY KEY (id),
    FOREIGN KEY (admin_action_id) REFERENCES admin_actions(id),
    FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE mail_templates (
    template_key VARCHAR(100) NOT NULL,
    display_name VARCHAR(150) NOT NULL,
    description  TEXT,
    body         TEXT         NOT NULL,
    sort_order   SMALLINT     NOT NULL DEFAULT 0,
    is_enabled   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (template_key)
);

CREATE TABLE mail_campaigns (
    id              UUID                 NOT NULL DEFAULT gen_random_uuid(),
    template_key    VARCHAR(100),
    subject         VARCHAR(200)         NOT NULL,
    body            TEXT                 NOT NULL,
    created_by      UUID,
    status          mail_campaign_status NOT NULL DEFAULT 'draft',
    scheduled_at    TIMESTAMPTZ,
    sent_at         TIMESTAMPTZ,
    recipient_count INTEGER              NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ          NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ          NOT NULL DEFAULT NOW(),
    CONSTRAINT mail_campaigns_recipient_count_check CHECK ((recipient_count >= 0)),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (template_key) REFERENCES mail_templates(template_key) ON DELETE SET NULL
);

CREATE TABLE mail_campaign_recipients (
    id                UUID                           NOT NULL DEFAULT gen_random_uuid(),
    campaign_id       UUID                           NOT NULL,
    user_id           UUID,
    resolved_email    VARCHAR(255),
    status            mail_campaign_recipient_status NOT NULL DEFAULT 'pending',
    email_delivery_id UUID,
    created_at        TIMESTAMPTZ                    NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uq_mail_campaign_recipients_campaign_user UNIQUE (campaign_id, user_id),
    FOREIGN KEY (campaign_id) REFERENCES mail_campaigns(id) ON DELETE CASCADE,
    FOREIGN KEY (email_delivery_id) REFERENCES email_deliveries(id) ON DELETE SET NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- ============================================================
-- MODULE: INTEREST TAXONOMY
-- ============================================================

-- Interest taxonomy (e.g. Fashion > Streetwear)
CREATE TABLE categories (
    id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    name       VARCHAR(100) NOT NULL,
    slug       VARCHAR(100) NOT NULL,
    parent_id  UUID,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (name),
    UNIQUE (slug),
    FOREIGN KEY (parent_id) REFERENCES categories(id)
);

-- User interest weights (updated by ML jobs or explicit selection)
CREATE TABLE user_interests (
    user_id     UUID         NOT NULL,
    category_id UUID         NOT NULL,
    score       NUMERIC(5,2) NOT NULL DEFAULT 1.0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, category_id),
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Post categorisation (assigned during upload or by ML classifier)
CREATE TABLE post_categories (
    post_id     UUID         NOT NULL,
    category_id UUID         NOT NULL,
    confidence  NUMERIC(4,3) NOT NULL DEFAULT 1.0,
    PRIMARY KEY (post_id, category_id),
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- User tags within a post image
CREATE TABLE post_user_tags (
    post_id        UUID         NOT NULL,
    tagged_user_id UUID         NOT NULL,
    media_asset_id UUID,
    x_position     NUMERIC(5,2),
    y_position     NUMERIC(5,2),
    PRIMARY KEY (post_id, tagged_user_id),
    FOREIGN KEY (media_asset_id) REFERENCES media_assets(id),
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (tagged_user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: RECOMMENDATION SYSTEM & USER BEHAVIOR
-- ============================================================

-- Raw event stream for user behavior
-- Partitioned by month: high-volume, append-only, analytics-friendly
CREATE TABLE user_events (
    id          UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL,
    session_id  UUID,
    event_type  event_type  NOT NULL,
    entity_type VARCHAR(50),
    entity_id   UUID,
    metadata    JSONB,
    ip_address  INET,
    user_agent  TEXT,
    platform    VARCHAR(10),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT user_events_platform_check CHECK (((platform)::TEXT = ANY ((ARRAY['ios'::VARCHAR, 'android'::VARCHAR, 'web'::VARCHAR])::TEXT[]))),
    PRIMARY KEY (id, created_at),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) PARTITION BY RANGE (created_at);

-- Aggregated post interaction scores (updated by background scheduler)
-- Powers feed ranking and Explore page recommendation
CREATE TABLE post_interaction_scores (
    post_id          UUID          NOT NULL,
    view_score       NUMERIC(10,4) NOT NULL DEFAULT 0,
    engagement_score NUMERIC(10,4) NOT NULL DEFAULT 0,
    recency_score    NUMERIC(10,4) NOT NULL DEFAULT 0,
    total_score      NUMERIC(10,4) NOT NULL DEFAULT 0,
    computed_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    PRIMARY KEY (post_id),
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- User-to-user similarity for collaborative filtering (populated by ML jobs)
-- Constraint: store only (min_id, max_id) to avoid (A,B) / (B,A) duplication
CREATE TABLE user_similarity (
    user_id_a        UUID         NOT NULL,
    user_id_b        UUID         NOT NULL,
    similarity_score NUMERIC(6,4) NOT NULL,
    computed_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT user_similarity_check CHECK ((user_id_a < user_id_b)),
    CONSTRAINT user_similarity_similarity_score_check CHECK (((similarity_score >= (0)::NUMERIC) AND (similarity_score <= (1)::NUMERIC))),
    PRIMARY KEY (user_id_a, user_id_b),
    FOREIGN KEY (user_id_a) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id_b) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_hashtag_affinity (
    user_id      UUID          NOT NULL,
    hashtag_id   UUID          NOT NULL,
    score        NUMERIC(10,8) NOT NULL,
    weight       NUMERIC(14,6) NOT NULL,
    event_count  INTEGER       NOT NULL,
    window_start TIMESTAMPTZ   NOT NULL,
    window_end   TIMESTAMPTZ   NOT NULL,
    computed_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT user_hashtag_affinity_event_count_check CHECK ((event_count >= 0)),
    CONSTRAINT user_hashtag_affinity_score_check CHECK (((score >= (0)::NUMERIC) AND (score <= (1)::NUMERIC))),
    CONSTRAINT user_hashtag_affinity_weight_check CHECK ((weight >= (0)::NUMERIC)),
    CONSTRAINT user_hashtag_affinity_window_order CHECK ((window_end > window_start)),
    PRIMARY KEY (user_id, hashtag_id),
    FOREIGN KEY (hashtag_id) REFERENCES hashtags(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_suggestions (
    user_id      UUID          NOT NULL,
    suggested_id UUID          NOT NULL,
    rank         SMALLINT      NOT NULL,
    score        NUMERIC(12,8) NOT NULL,
    sources      TEXT          NOT NULL,
    computed_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT user_suggestions_not_self CHECK ((user_id <> suggested_id)),
    CONSTRAINT user_suggestions_rank_positive CHECK ((rank > 0)),
    PRIMARY KEY (user_id, suggested_id),
    FOREIGN KEY (suggested_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE suggestion_dismissals (
    user_id      UUID        NOT NULL,
    dismissed_id UUID        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT suggestion_dismissals_not_self CHECK ((user_id <> dismissed_id)),
    PRIMARY KEY (user_id, dismissed_id),
    FOREIGN KEY (dismissed_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- MODULE: COMMON / OUTBOX
-- ============================================================

CREATE TABLE outbox_events (
    id             UUID         NOT NULL DEFAULT gen_random_uuid(),
    event_id       UUID         NOT NULL,
    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id   UUID         NOT NULL,
    event_type     VARCHAR(150) NOT NULL,
    routing_key    VARCHAR(150) NOT NULL,
    payload        JSONB        NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING'::VARCHAR,
    attempt_count  INTEGER      NOT NULL DEFAULT 0,
    next_retry_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_error     TEXT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    published_at   TIMESTAMPTZ,
    claim_id       UUID,
    claimed_at     TIMESTAMPTZ,
    claimed_until  TIMESTAMPTZ,
    CONSTRAINT chk_outbox_events_processing_claim CHECK ((((status)::TEXT <> 'PROCESSING'::TEXT) OR ((claim_id IS NOT NULL) AND (claimed_at IS NOT NULL) AND (claimed_until IS NOT NULL) AND (claimed_until > claimed_at)))),
    CONSTRAINT outbox_events_attempt_count_check CHECK ((attempt_count >= 0)),
    CONSTRAINT outbox_events_check CHECK (((((status)::TEXT = 'PUBLISHED'::TEXT) AND (published_at IS NOT NULL)) OR (((status)::TEXT <> 'PUBLISHED'::TEXT) AND (published_at IS NULL)))),
    CONSTRAINT outbox_events_status_check CHECK (((status)::TEXT = ANY ((ARRAY['PENDING'::VARCHAR, 'PROCESSING'::VARCHAR, 'PUBLISHED'::VARCHAR, 'DEAD'::VARCHAR])::TEXT[]))),
    PRIMARY KEY (id),
    UNIQUE (event_id)
);

CREATE TABLE processed_messages (
    id            UUID         NOT NULL DEFAULT gen_random_uuid(),
    consumer_name VARCHAR(100) NOT NULL,
    event_id      UUID         NOT NULL,
    event_type    VARCHAR(150) NOT NULL,
    processed_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (consumer_name, event_id)
);

-- ============================================================
-- FORWARD-REFERENCING FOREIGN KEYS
-- ============================================================

-- These reference a table declared later under a different module banner, so they
-- are attached here rather than inline. Grouping by module is what puts them out of
-- order; the constraint itself is no different from an inline one.

ALTER TABLE users ADD FOREIGN KEY (verified_category) REFERENCES verification_categories(category_key);

-- ============================================================
-- PARTITIONS (declared, not runtime)
-- ============================================================

CREATE TABLE user_events_default PARTITION OF user_events DEFAULT;

-- ============================================================
-- INDEXES
-- ============================================================

-- indexes on stories
CREATE INDEX idx_stories_expires ON stories USING btree (expires_at) WHERE (deleted_at IS NULL);
-- stories
CREATE INDEX idx_stories_user ON stories USING btree (user_id, created_at DESC) WHERE (deleted_at IS NULL);

-- indexes on users
CREATE INDEX idx_users_created_at ON users USING btree (created_at DESC);
CREATE INDEX idx_users_email ON users USING btree (email);
-- Administrative account surface (V57). Built CONCURRENTLY by the migration; plain here because
-- this file describes the final state rather than how to reach it on a live database.
-- Email had no trigram index before this, so an administrator searching by address paid a parallel
-- sequential scan of the whole table: measured at 77 ms against 200,000 rows, 0.3 ms with it.
CREATE INDEX idx_users_email_trgm ON users USING gin (email gin_trgm_ops);
CREATE INDEX idx_users_fts ON users USING gin (to_tsvector('simple'::regconfig, (((COALESCE(username, ''::VARCHAR))::TEXT || ' '::TEXT) || (COALESCE(display_name, ''::VARCHAR))::TEXT)));
-- Role-filtered account listing (V72). The rare role is the decisive case: an administrator
-- filters by moderator or admin precisely because those are the accounts worth looking at, and
-- without this the plan discards rows in proportion to the whole table rather than to the role.
CREATE INDEX idx_users_role_created ON users USING btree (role, created_at DESC, id DESC);
CREATE INDEX idx_users_status ON users USING btree (status) WHERE (deleted_at IS NULL);
-- Turns a status-filtered account page from an Incremental Sort that discards over a thousand rows
-- per page into a single index seek that carries the keyset tiebreaker.
CREATE INDEX idx_users_status_created ON users USING btree (status, created_at DESC, id DESC);
-- Partial, so an indefinite suspension (null deadline) is absent from the index rather than
-- filtered out of it. Bounds the reinstatement sweep's candidate scan.
CREATE INDEX idx_users_suspended_until ON users USING btree (suspended_until) WHERE (suspended_until IS NOT NULL);
-- users
CREATE INDEX idx_users_username ON users USING btree (username) WHERE (deleted_at IS NULL);
CREATE INDEX idx_users_username_trgm ON users USING gin (username gin_trgm_ops);
CREATE INDEX idx_users_verified_followers ON users USING btree (verified_category, follower_count DESC) WHERE ((is_verified = true) AND (deleted_at IS NULL));
-- Same table-wide shape and rationale as idx_users_username_lower, applied to email: soft delete
-- does not release an email either, and email identity is case-insensitive per RFC 5321 and every
-- major mail provider's practice. users_email_key (raw UNIQUE column constraint above) is retained
-- as a structural guard and is implied by this index.
CREATE UNIQUE INDEX idx_users_email_lower ON users USING btree (lower((email)::TEXT));
-- Table-wide (not partial on deleted_at) so a soft-deleted account's username stays reserved,
-- matching the documented soft-delete retention policy; users_username_key (raw UNIQUE column
-- constraint above) is retained as a structural guard and is implied by this index.
CREATE UNIQUE INDEX idx_users_username_lower ON users USING btree (lower((username)::TEXT));

-- indexes on admin_actions
-- admin_actions
CREATE INDEX idx_admin_actions_admin ON admin_actions USING btree (admin_id, created_at DESC);
-- The administrator audit listing (V74), which sets none of the optional filters and so cannot
-- use the index above. admin_actions is append-only with no retention, so the scan this replaces
-- grows monotonically and forever.
CREATE INDEX idx_admin_actions_created ON admin_actions USING btree (created_at DESC, id DESC);
CREATE INDEX idx_admin_actions_target ON admin_actions USING btree (target_user_id) WHERE (target_user_id IS NOT NULL);
CREATE INDEX idx_admin_actions_target_created ON admin_actions USING btree (target_user_id, created_at DESC, id DESC) WHERE (target_user_id IS NOT NULL);

-- indexes on blocks
CREATE INDEX idx_blocks_blocked ON blocks USING btree (blocked_id);
-- blocks
CREATE INDEX idx_blocks_blocker ON blocks USING btree (blocker_id);
CREATE INDEX idx_blocks_blocker_created_blocked ON blocks USING btree (blocker_id, created_at DESC, blocked_id DESC);

-- indexes on comment_likes
-- comment_likes
CREATE INDEX idx_comment_likes_comment ON comment_likes USING btree (comment_id);
CREATE INDEX idx_comment_likes_user ON comment_likes USING btree (user_id);

-- indexes on comment_write_idempotency
-- comment_write_idempotency
CREATE INDEX idx_comment_idempotency_created ON comment_write_idempotency USING btree (created_at);

-- indexes on comments
CREATE INDEX idx_comments_parent ON comments USING btree (parent_id, created_at) WHERE ((parent_id IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX idx_comments_parent_id ON comments USING btree (parent_id, created_at DESC, id DESC) WHERE ((parent_id IS NOT NULL) AND (deleted_at IS NULL));
CREATE INDEX idx_comments_post_moderation ON comments USING btree (post_id, moderation_status, created_at DESC) WHERE (deleted_at IS NULL);
-- comments
CREATE INDEX idx_comments_post_root ON comments USING btree (post_id, created_at) WHERE ((parent_id IS NULL) AND (deleted_at IS NULL));
CREATE INDEX idx_comments_post_root_id ON comments USING btree (post_id, created_at DESC, id DESC) WHERE ((parent_id IS NULL) AND (deleted_at IS NULL));
-- Serves the pinned "top comments" block: the most-liked eligible top-level comments on a post.
CREATE INDEX idx_comments_post_top_liked ON comments USING btree (post_id, like_count DESC, created_at DESC, id DESC) WHERE ((parent_id IS NULL) AND (deleted_at IS NULL) AND ((moderation_status)::TEXT = 'approved'::TEXT));
CREATE INDEX idx_comments_root ON comments USING btree (root_id) WHERE (root_id IS NOT NULL);
CREATE INDEX idx_comments_user ON comments USING btree (user_id);

-- indexes on conversation_participants
-- conversation_participants
CREATE INDEX idx_conv_part_user ON conversation_participants USING btree (user_id, last_read_at DESC) WHERE (left_at IS NULL);

-- indexes on conversations
-- conversations
CREATE INDEX idx_conversations_updated ON conversations USING btree (last_message_at DESC NULLS LAST);
-- Every conversation is 1-1, so the pair key alone identifies it; losing this index would let a
-- pair silently hold two separate threads.
CREATE UNIQUE INDEX idx_conversations_direct_pair_key ON conversations USING btree (direct_pair_key) WHERE (direct_pair_key IS NOT NULL);

-- indexes on follows
CREATE INDEX idx_follows_follower ON follows USING btree (follower_id, status, created_at DESC);
CREATE INDEX idx_follows_follower_created_following ON follows USING btree (follower_id, status, created_at DESC, following_id DESC);
-- follows
CREATE INDEX idx_follows_following ON follows USING btree (following_id, status, created_at DESC);
CREATE INDEX idx_follows_following_created_follower ON follows USING btree (following_id, status, created_at DESC, follower_id DESC);

-- indexes on hashtags
CREATE INDEX idx_hashtags_active_post_count ON hashtags USING btree (post_count DESC, name) WHERE (status = 'active'::hashtag_status);
-- Administrative registry listing with no status filter (V72). idx_hashtags_status_created
-- leads with status, which an unfiltered listing cannot use at all.
CREATE INDEX idx_hashtags_created ON hashtags USING btree (created_at DESC, id DESC);
-- hashtags
CREATE INDEX idx_hashtags_name ON hashtags USING btree (name);
CREATE INDEX idx_hashtags_name_trgm ON hashtags USING gin (name gin_trgm_ops);
CREATE INDEX idx_hashtags_post_count ON hashtags USING btree (post_count DESC);
CREATE INDEX idx_hashtags_status_created ON hashtags USING btree (status, created_at DESC, id DESC);

-- indexes on mail_campaign_recipients
CREATE INDEX idx_mail_campaign_recipients_campaign ON mail_campaign_recipients USING btree (campaign_id);

-- indexes on mail_campaigns
CREATE INDEX idx_mail_campaigns_due ON mail_campaigns USING btree (scheduled_at) WHERE (status = 'scheduled'::mail_campaign_status);

-- indexes on media_assets
-- media_assets
CREATE INDEX idx_media_assets_user ON media_assets USING btree (user_id, created_at DESC);

-- indexes on message_write_idempotency
CREATE INDEX idx_message_idempotency_created ON message_write_idempotency USING btree (created_at);

-- indexes on messages
-- messages
CREATE INDEX idx_messages_conversation ON messages USING btree (conversation_id, created_at DESC) WHERE (is_deleted = false);
CREATE INDEX idx_messages_sender ON messages USING btree (sender_id);

-- indexes on notifications
-- notifications
CREATE INDEX idx_notifications_recipient ON notifications USING btree (recipient_id, created_at DESC);
CREATE INDEX idx_notifications_recipient_created_id ON notifications USING btree (recipient_id, created_at DESC, id DESC);
CREATE INDEX idx_notifications_unread ON notifications USING btree (recipient_id, created_at DESC) WHERE (is_read = false);

-- indexes on outbox_events
CREATE INDEX idx_outbox_events_aggregate ON outbox_events USING btree (aggregate_type, aggregate_id, created_at);
-- outbox_events
CREATE INDEX idx_outbox_events_publish_scan ON outbox_events USING btree (status, next_retry_at, created_at) WHERE ((status)::TEXT = ANY ((ARRAY['PENDING'::VARCHAR, 'PROCESSING'::VARCHAR])::TEXT[]));

-- indexes on reports
CREATE INDEX idx_reports_entity ON reports USING btree (entity_id, report_type);
-- Serves both readers of the escalated queue: the administrator listing, oldest first, and the
-- counter that is the only signal an escalated report is waiting (V66).
CREATE INDEX idx_reports_escalated ON reports USING btree (created_at, id) WHERE (status = 'escalated'::report_status);
CREATE INDEX idx_reports_escalated_by ON reports USING btree (escalated_by, escalated_at DESC, id DESC) WHERE (escalated_by IS NOT NULL);
-- The moderator queue (V73). A set of statuses with one global ordering cannot be walked from
-- idx_reports_status, which leads with status: the entries are ordered within each status, not
-- across them. Partial on the same two statuses ReportStatus.OPEN_QUEUE names; a status added there
-- without being added here returns the queue to a sequential scan of every report ever filed.
CREATE INDEX idx_reports_open_queue ON reports USING btree (created_at DESC, id DESC) WHERE (status = ANY (ARRAY['pending'::report_status, 'reviewing'::report_status]));
CREATE INDEX idx_reports_reporter ON reports USING btree (reporter_id);
-- reports
CREATE INDEX idx_reports_status ON reports USING btree (status, created_at DESC);
CREATE UNIQUE INDEX uq_reports_reporter_type_entity ON reports USING btree (reporter_id, report_type, entity_id) WHERE (status = ANY (ARRAY['pending'::report_status, 'reviewing'::report_status, 'escalated'::report_status]));

-- indexes on platform_stats
-- platform_stats
-- The series read (V71). The primary key leads with bucket_start, so it can bound the range but
-- cannot narrow to one metric without filtering every metric written in that range. This leads with
-- the two equality columns and carries the range and the ordering.
CREATE INDEX idx_platform_stats_series ON platform_stats USING btree (metric_key, granularity, bucket_start DESC);

-- indexes on post_edit_history
-- post_edit_history
CREATE INDEX idx_post_edit_history_post_edited ON post_edit_history USING btree (post_id, edited_at DESC);
CREATE INDEX idx_post_edit_history_post_edited_id ON post_edit_history USING btree (post_id, edited_at DESC, id DESC);

-- indexes on post_hashtags
CREATE INDEX idx_post_hashtags_tag ON post_hashtags USING btree (hashtag_id, post_id);

-- indexes on post_interaction_scores
-- post_interaction_scores
CREATE INDEX idx_post_scores_total ON post_interaction_scores USING btree (total_score DESC);

-- indexes on post_likes
-- post_likes
CREATE INDEX idx_post_likes_post ON post_likes USING btree (post_id, created_at DESC);
CREATE INDEX idx_post_likes_post_created_user ON post_likes USING btree (post_id, created_at DESC, user_id DESC);
CREATE INDEX idx_post_likes_user ON post_likes USING btree (user_id, created_at DESC);
CREATE INDEX idx_post_likes_user_created_post ON post_likes USING btree (user_id, created_at DESC, post_id DESC);

-- indexes on post_media
-- post_media
CREATE INDEX idx_post_media_post ON post_media USING btree (post_id, "position");

-- indexes on post_saves
-- post_saves
CREATE INDEX idx_post_saves_user ON post_saves USING btree (user_id, created_at DESC);
CREATE INDEX idx_post_saves_user_created_post ON post_saves USING btree (user_id, created_at DESC, post_id DESC);

-- indexes on posts
CREATE INDEX idx_posts_created_at ON posts USING btree (created_at DESC) WHERE ((status = 'published'::post_status) AND (deleted_at IS NULL));
CREATE INDEX idx_posts_status ON posts USING btree (status) WHERE (deleted_at IS NULL);
CREATE INDEX idx_posts_user_created_id ON posts USING btree (user_id, created_at DESC, id DESC) WHERE ((status = 'published'::post_status) AND (deleted_at IS NULL));
-- posts
CREATE INDEX idx_posts_user_feed ON posts USING btree (user_id, created_at DESC) WHERE ((status = 'published'::post_status) AND (deleted_at IS NULL));

-- indexes on processed_messages
-- processed_messages
CREATE INDEX idx_processed_messages_event ON processed_messages USING btree (event_id);
CREATE INDEX idx_processed_messages_processed_at ON processed_messages USING btree (processed_at);

-- indexes on refresh_tokens
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens USING btree (expires_at);
-- refresh_tokens
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens USING btree (user_id) WHERE (revoked_at IS NULL);

-- indexes on story_views
-- story_views
CREATE INDEX idx_story_views_story_viewed_viewer ON story_views USING btree (story_id, viewed_at DESC, viewer_id DESC);

-- indexes on support_tickets
CREATE INDEX idx_support_tickets_admin_action ON support_tickets USING btree (admin_action_id) WHERE (admin_action_id IS NOT NULL);
CREATE INDEX idx_support_tickets_assigned ON support_tickets USING btree (assigned_to, created_at DESC, id DESC) WHERE (assigned_to IS NOT NULL);
CREATE INDEX idx_support_tickets_status_created ON support_tickets USING btree (status, created_at DESC, id DESC);
CREATE INDEX idx_support_tickets_user_created ON support_tickets USING btree (user_id, created_at DESC, id DESC) WHERE (user_id IS NOT NULL);
CREATE UNIQUE INDEX uq_support_tickets_one_open_support_per_user ON support_tickets USING btree (user_id) WHERE ((user_id IS NOT NULL) AND (category <> 'verification_request'::support_category) AND (status = ANY (ARRAY['open'::support_ticket_status, 'in_progress'::support_ticket_status, 'escalated'::support_ticket_status])));
CREATE UNIQUE INDEX uq_support_tickets_one_open_verification_per_user ON support_tickets USING btree (user_id) WHERE ((user_id IS NOT NULL) AND (category = 'verification_request'::support_category) AND (status = ANY (ARRAY['open'::support_ticket_status, 'in_progress'::support_ticket_status, 'escalated'::support_ticket_status])));

-- indexes on user_events
CREATE INDEX idx_user_events_entity ON user_events USING btree (entity_type, entity_id, created_at DESC) WHERE (entity_id IS NOT NULL);
CREATE INDEX idx_user_events_type ON user_events USING btree (event_type, created_at DESC);
-- user_events (applied per partition automatically)
CREATE INDEX idx_user_events_user ON user_events USING btree (user_id, created_at DESC);

-- indexes on user_hashtag_affinity
CREATE INDEX idx_user_hashtag_affinity_hashtag_user ON user_hashtag_affinity USING btree (hashtag_id, user_id) INCLUDE (score);
CREATE INDEX idx_user_hashtag_affinity_user_score ON user_hashtag_affinity USING btree (user_id, score DESC, hashtag_id DESC);

-- indexes on user_settings
CREATE UNIQUE INDEX uq_user_settings_unsubscribe_token ON user_settings USING btree (unsubscribe_token) WHERE (unsubscribe_token IS NOT NULL);

-- indexes on user_similarity
-- user_similarity
CREATE INDEX idx_user_sim_score ON user_similarity USING btree (user_id_a, similarity_score DESC);

-- indexes on user_strikes
CREATE INDEX idx_user_strikes_active ON user_strikes USING btree (user_id, created_at DESC) WHERE (revoked_at IS NULL);
-- Correctness guard, not a performance index: two concurrent warnings can both read an active
-- count of two and both try to issue the same strike number. Partial on revoked_at IS NULL so
-- revoking a strike frees its number for re-issue.
CREATE UNIQUE INDEX uq_user_strikes_active_number ON user_strikes USING btree (user_id, strike_number) WHERE (revoked_at IS NULL);

-- indexes on user_suggestions
CREATE INDEX idx_user_suggestions_user_rank ON user_suggestions USING btree (user_id, rank);

-- indexes on user_verifications
CREATE INDEX idx_user_verifications_user_granted ON user_verifications USING btree (user_id, granted_at DESC);
CREATE UNIQUE INDEX uq_user_verifications_active ON user_verifications USING btree (user_id) WHERE (revoked_at IS NULL);

-- indexes on user_warnings
CREATE INDEX idx_user_warnings_active ON user_warnings USING btree (user_id, created_at DESC) WHERE (revoked_at IS NULL);

-- indexes on verification_requests
CREATE INDEX idx_verification_requests_user_created ON verification_requests USING btree (user_id, created_at DESC);

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Comment like_count
CREATE FUNCTION fn_comment_like_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE comments SET like_count = like_count + 1 WHERE id = NEW.comment_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE comments SET like_count = GREATEST(like_count - 1, 0) WHERE id = OLD.comment_id;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Comment reply_count (on parent)
CREATE FUNCTION fn_comment_reply_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    was_visible BOOLEAN;
    now_visible BOOLEAN;
BEGIN
    IF TG_OP = 'INSERT' AND NEW.parent_id IS NOT NULL THEN
        IF NEW.deleted_at IS NULL AND NEW.admin_removed_at IS NULL THEN
            UPDATE comments SET reply_count = reply_count + 1 WHERE id = NEW.parent_id;
        END IF;
    ELSIF TG_OP = 'DELETE' AND OLD.parent_id IS NOT NULL THEN
        IF OLD.deleted_at IS NULL AND OLD.admin_removed_at IS NULL THEN
            UPDATE comments SET reply_count = GREATEST(reply_count - 1, 0) WHERE id = OLD.parent_id;
        END IF;
    ELSIF TG_OP = 'UPDATE' AND NEW.parent_id IS NOT NULL THEN
        was_visible := OLD.deleted_at IS NULL AND OLD.admin_removed_at IS NULL;
        now_visible := NEW.deleted_at IS NULL AND NEW.admin_removed_at IS NULL;
        IF was_visible AND NOT now_visible THEN
            UPDATE comments SET reply_count = GREATEST(reply_count - 1, 0) WHERE id = NEW.parent_id;
        ELSIF now_visible AND NOT was_visible THEN
            UPDATE comments SET reply_count = reply_count + 1 WHERE id = NEW.parent_id;
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Update conversations.last_message_at on new message
CREATE FUNCTION fn_conversation_last_message() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE conversations
    SET last_message_at = NEW.created_at,
        updated_at      = NEW.created_at
    WHERE id = NEW.conversation_id;
    RETURN NEW;
END;
$$;

-- Follow counter maintenance. Both users rows are locked in id order before either is written,
-- so two people following each other back at the same instant queue behind each other instead
-- of deadlocking on the opposite lock order.
CREATE FUNCTION fn_follow_counts() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    follower_key  UUID;
    following_key UUID;
BEGIN
    IF TG_OP = 'DELETE' THEN
        follower_key  := OLD.follower_id;
        following_key := OLD.following_id;
    ELSE
        follower_key  := NEW.follower_id;
        following_key := NEW.following_id;
    END IF;

    -- Both rows locked in id order before either is written, so the two directions of a pair can
    -- never hold one lock each and wait on the other.
    PERFORM 1 FROM users
    WHERE id IN (follower_key, following_key)
    ORDER BY id
    FOR NO KEY UPDATE;

    IF TG_OP = 'INSERT' AND NEW.status = 'accepted' THEN
        UPDATE users SET following_count = following_count + 1 WHERE id = NEW.follower_id;
        UPDATE users SET follower_count  = follower_count  + 1 WHERE id = NEW.following_id;

    ELSIF TG_OP = 'DELETE' AND OLD.status = 'accepted' THEN
        UPDATE users SET following_count = GREATEST(following_count - 1, 0) WHERE id = OLD.follower_id;
        UPDATE users SET follower_count  = GREATEST(follower_count  - 1, 0) WHERE id = OLD.following_id;

    ELSIF TG_OP = 'UPDATE' THEN
        IF OLD.status <> 'accepted' AND NEW.status = 'accepted' THEN
            UPDATE users SET following_count = following_count + 1 WHERE id = NEW.follower_id;
            UPDATE users SET follower_count  = follower_count  + 1 WHERE id = NEW.following_id;
        ELSIF OLD.status = 'accepted' AND NEW.status <> 'accepted' THEN
            UPDATE users SET following_count = GREATEST(following_count - 1, 0) WHERE id = NEW.follower_id;
            UPDATE users SET follower_count  = GREATEST(follower_count  - 1, 0) WHERE id = NEW.following_id;
        END IF;
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Hashtag post_count
CREATE FUNCTION fn_hashtag_post_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE hashtags SET post_count = post_count + 1 WHERE id = NEW.hashtag_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE hashtags SET post_count = GREATEST(post_count - 1, 0) WHERE id = OLD.hashtag_id;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Post comment_count
CREATE FUNCTION fn_post_comment_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    was_visible BOOLEAN;
    now_visible BOOLEAN;
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.deleted_at IS NULL AND NEW.admin_removed_at IS NULL THEN
            UPDATE posts SET comment_count = comment_count + 1 WHERE id = NEW.post_id;
        END IF;
    ELSIF TG_OP = 'DELETE' THEN
        IF OLD.deleted_at IS NULL AND OLD.admin_removed_at IS NULL THEN
            UPDATE posts SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = OLD.post_id;
        END IF;
    ELSIF TG_OP = 'UPDATE' THEN
        was_visible := OLD.deleted_at IS NULL AND OLD.admin_removed_at IS NULL;
        now_visible := NEW.deleted_at IS NULL AND NEW.admin_removed_at IS NULL;
        IF was_visible AND NOT now_visible THEN
            UPDATE posts SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = NEW.post_id;
        ELSIF now_visible AND NOT was_visible THEN
            UPDATE posts SET comment_count = comment_count + 1 WHERE id = NEW.post_id;
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Post count on users
CREATE FUNCTION fn_post_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' AND NEW.status = 'published' AND NEW.deleted_at IS NULL THEN
        UPDATE users SET post_count = post_count + 1 WHERE id = NEW.user_id;

    ELSIF TG_OP = 'DELETE' AND OLD.status = 'published' AND OLD.deleted_at IS NULL THEN
        UPDATE users SET post_count = GREATEST(post_count - 1, 0) WHERE id = OLD.user_id;

    ELSIF TG_OP = 'UPDATE' THEN
        IF (OLD.status <> 'published' OR OLD.deleted_at IS NOT NULL)
            AND NEW.status = 'published' AND NEW.deleted_at IS NULL THEN
            UPDATE users SET post_count = post_count + 1 WHERE id = NEW.user_id;
        ELSIF OLD.status = 'published' AND OLD.deleted_at IS NULL
            AND (NEW.status <> 'published' OR NEW.deleted_at IS NOT NULL) THEN
            UPDATE users SET post_count = GREATEST(post_count - 1, 0) WHERE id = NEW.user_id;
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Post like_count
CREATE FUNCTION fn_post_like_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE posts SET like_count = like_count + 1 WHERE id = NEW.post_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE posts SET like_count = GREATEST(like_count - 1, 0) WHERE id = OLD.post_id;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Post save_count
CREATE FUNCTION fn_post_save_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE posts SET save_count = save_count + 1 WHERE id = NEW.post_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE posts SET save_count = GREATEST(save_count - 1, 0) WHERE id = OLD.post_id;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Keeps stories.like_count in step with story_likes, the same way fn_post_like_count does for
-- posts. Counters are trigger-maintained and never written from application code (V49).
CREATE FUNCTION fn_story_like_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE stories SET like_count = like_count + 1 WHERE id = NEW.story_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE stories SET like_count = GREATEST(like_count - 1, 0) WHERE id = OLD.story_id;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

-- Story view_count
CREATE FUNCTION fn_story_view_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE stories SET view_count = view_count + 1 WHERE id = NEW.story_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE stories SET view_count = GREATEST(view_count - 1, 0) WHERE id = OLD.story_id;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE FUNCTION fn_sync_user_verification() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
    affected UUID;
BEGIN
    affected := COALESCE(NEW.user_id, OLD.user_id);
    UPDATE users u
       SET is_verified = v.active IS NOT NULL,
           verified_category = v.active
      FROM (
          SELECT (SELECT category_key
                    FROM user_verifications
                   WHERE user_id = affected AND revoked_at IS NULL
                   ORDER BY granted_at DESC
                   LIMIT 1) AS active
      ) v
     WHERE u.id = affected;
    RETURN NULL;
END;
$$;

-- Generic updated_at updater
CREATE FUNCTION fn_update_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

SET default_tablespace = '';

SET default_table_access_method = heap;

-- ============================================================
-- TRIGGERS
-- ============================================================

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

CREATE TRIGGER trg_comment_like_count AFTER INSERT OR DELETE ON comment_likes FOR EACH ROW EXECUTE FUNCTION fn_comment_like_count();

CREATE TRIGGER trg_comment_reply_count AFTER INSERT OR DELETE OR UPDATE ON comments FOR EACH ROW EXECUTE FUNCTION fn_comment_reply_count();

CREATE TRIGGER trg_comments_updated_at BEFORE UPDATE ON comments FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

CREATE TRIGGER trg_post_comment_count AFTER INSERT OR DELETE OR UPDATE ON comments FOR EACH ROW EXECUTE FUNCTION fn_post_comment_count();

CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON conversations FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

CREATE TRIGGER trg_feature_flags_updated_at BEFORE UPDATE ON feature_flags FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

CREATE TRIGGER trg_follow_counts AFTER INSERT OR DELETE OR UPDATE ON follows FOR EACH ROW EXECUTE FUNCTION fn_follow_counts();

CREATE TRIGGER trg_mail_campaigns_updated_at BEFORE UPDATE ON mail_campaigns FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

CREATE TRIGGER trg_mail_templates_updated_at BEFORE UPDATE ON mail_templates FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

CREATE TRIGGER trg_conversation_last_message AFTER INSERT ON messages FOR EACH ROW EXECUTE FUNCTION fn_conversation_last_message();

CREATE TRIGGER trg_hashtag_post_count AFTER INSERT OR DELETE ON post_hashtags FOR EACH ROW EXECUTE FUNCTION fn_hashtag_post_count();

CREATE TRIGGER trg_post_like_count AFTER INSERT OR DELETE ON post_likes FOR EACH ROW EXECUTE FUNCTION fn_post_like_count();

CREATE TRIGGER trg_post_save_count AFTER INSERT OR DELETE ON post_saves FOR EACH ROW EXECUTE FUNCTION fn_post_save_count();

CREATE TRIGGER trg_post_count AFTER INSERT OR DELETE OR UPDATE ON posts FOR EACH ROW EXECUTE FUNCTION fn_post_count();

CREATE TRIGGER trg_posts_updated_at BEFORE UPDATE ON posts FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

CREATE TRIGGER trg_story_like_count AFTER INSERT OR DELETE ON story_likes FOR EACH ROW EXECUTE FUNCTION fn_story_like_count();

CREATE TRIGGER trg_story_view_count AFTER INSERT OR DELETE ON story_views FOR EACH ROW EXECUTE FUNCTION fn_story_view_count();

CREATE TRIGGER trg_support_tickets_updated_at BEFORE UPDATE ON support_tickets FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

CREATE TRIGGER trg_system_settings_updated_at BEFORE UPDATE ON system_settings FOR EACH ROW EXECUTE FUNCTION fn_update_updated_at();

CREATE TRIGGER trg_user_verification_sync AFTER INSERT OR DELETE OR UPDATE ON user_verifications FOR EACH ROW EXECUTE FUNCTION fn_sync_user_verification();

-- ============================================================
-- VIEWS
-- ============================================================

-- Active (non-expired, non-deleted) stories
CREATE VIEW active_stories AS
 SELECT s.id,
    s.user_id,
    s.media_asset_id,
    s.story_type,
    s.caption,
    s.view_count,
    s.expires_at,
    s.created_at,
    s.deleted_at,
    s.like_count,
    s.admin_removed_at,
    u.username,
    u.avatar_url
   FROM (stories s
     JOIN users u ON (((u.id = s.user_id) AND (u.deleted_at IS NULL))))
  WHERE ((s.deleted_at IS NULL) AND (s.admin_removed_at IS NULL) AND (s.expires_at > NOW()));

-- Pending follow requests (for private accounts)
CREATE VIEW pending_follow_requests AS
 SELECT f.follower_id,
    f.following_id,
    f.status,
    f.created_at,
    follower.username AS follower_username,
    follower.avatar_url AS follower_avatar
   FROM (follows f
     JOIN users follower ON (((follower.id = f.follower_id) AND (follower.deleted_at IS NULL))))
  WHERE (f.status = 'pending'::follow_status);

-- Pending moderation reports
CREATE VIEW pending_reports AS
 SELECT r.id,
    r.reporter_id,
    r.report_type,
    r.report_reason,
    r.entity_id,
    r.description,
    r.status,
    r.reviewed_by,
    r.reviewed_at,
    r.resolution_note,
    r.created_at,
    reporter.username AS reporter_username
   FROM (reports r
     JOIN users reporter ON (((reporter.id = r.reporter_id) AND (reporter.deleted_at IS NULL))))
  WHERE (r.status = 'pending'::report_status)
  ORDER BY r.created_at;

-- ============================================================
-- OBJECT COMMENTS
-- ============================================================

-- `COMMENT ON` text stored in the database itself, written by the migrations. It is
-- part of the schema, so it is reproduced verbatim rather than paraphrased.

COMMENT ON TYPE email_delivery_status IS 'Observable outcomes of one send attempt. pending is written before the provider call; sent carries a provider_message_id; failed carries error_text; throttled means the per-recipient window rejected it before any call; skipped means the recipient was ineligible, such as a soft-deleted account.';

COMMENT ON TYPE mail_campaign_recipient_status IS 'skipped_opted_out records an exclusion rather than dropping the row, so an administrator can see who was left out and why instead of wondering where a recipient went.';

COMMENT ON TYPE mail_campaign_status IS 'sending is the claim state. The scheduler moves scheduled to sending with a conditional update, so only one instance can ever claim a campaign; see mail_campaigns for why that matters here and not for platform_stats.';

COMMENT ON TYPE support_category IS 'What the ticket is about. The four appeal_ values are the restricted set: only an administrator may respond to or close one, because unban, unsuspend, revoke_warning and revoke_strike are all administrator-only actions and a moderator closing an appeal would be issuing a verdict they cannot execute.';

COMMENT ON TYPE support_source IS 'How the ticket arrived. signed_link means a single-use token from a moderation mail authorised exactly this one ticket against one audit row; it never minted a session.';

COMMENT ON TYPE support_ticket_status IS 'pending_confirmation belongs to the public form alone: the row exists but is invisible to staff until the submitter proves control of the address. answered and rejected are terminal, and terminal is what the one-open-ticket guard treats as closed.';

COMMENT ON COLUMN stories.admin_removed_at IS 'Set by administrative removal; independent of the owner-owned deleted_at. A story is hidden when either column is set, and expires_at continues to decide visibility independently of both.';

COMMENT ON COLUMN users.verified_category IS 'Denormalised from the account''s active user_verifications row by trg_user_verification_sync. Never written by application code. Null exactly when is_verified is false.';

COMMENT ON COLUMN comments.edited_at IS 'When the content was last changed by its author. NULL means never edited. Written by application code on the edit path only; unlike updated_at, no trigger touches it, so a like or a reply leaves it alone.';

COMMENT ON COLUMN comments.admin_removed_at IS 'Set by administrative removal; independent of the author-owned deleted_at. A comment is hidden when either column is set, and clearing this one never undoes the author''s own deletion.';

COMMENT ON COLUMN email_deliveries.recipient_user_id IS 'Nullable and ON DELETE SET NULL so a hard-deleted account does not erase the record that mail was sent to it; recipient_email preserves the destination.';

COMMENT ON COLUMN email_deliveries.admin_action_id IS 'The moderation decision this delivery announces, or NULL for mail with no audit row behind it, such as auth mail.';

COMMENT ON COLUMN email_deliveries.provider_message_id IS 'Identifier returned by the provider on acceptance. NULL for every status other than sent.';

COMMENT ON COLUMN email_deliveries.attempt_count IS 'Provider calls made for this row. Stays 0 for a row that never reached a call, which is what separates a throttled or skipped send from one the provider rejected.';

COMMENT ON COLUMN hashtags.pinned_at IS 'When an administrator pinned this hashtag platform-wide; NULL means not pinned.';

COMMENT ON COLUMN mail_campaign_recipients.resolved_email IS 'The address as it stood when the campaign was sent, not when it was drafted. Null while the recipient is still pending, and null for a recipient skipped before any address was read.';

COMMENT ON COLUMN mail_campaign_recipients.email_delivery_id IS 'Links to the send log row so a campaign recipient can be traced to the provider message id. Null for a skipped or still-pending recipient, which never reached a send.';

COMMENT ON COLUMN mail_campaigns.template_key IS 'Which sample this campaign started from, for reporting only. ON DELETE SET NULL because the campaign body is an independent snapshot and outlives the template it was copied from.';

COMMENT ON COLUMN mail_campaigns.body IS 'Markdown snapshot, immutable once the campaign leaves draft. A campaign is the record of what was actually sent, so editing it after the fact would make that record a lie.';

COMMENT ON COLUMN mail_campaigns.status IS 'The scheduler claims a campaign with a conditional UPDATE from scheduled to sending. That single-row transition is what makes a double send impossible: this codebase has no distributed scheduler lock, and unlike platform_stats a second run here would mail real people twice.';

COMMENT ON TABLE mail_templates IS 'Read-only samples seeded here. There is no administrator-facing create, update or delete in this release; campaigns consume a template by copying its body, so adding that CRUD later changes nothing about how campaigns read it.';

COMMENT ON COLUMN mail_templates.body IS 'Markdown, not HTML. The send and preview paths run one pipeline: CommonMark to HTML, then the OWASP sanitizer allowlist, then injection into the shared Thymeleaf layout.';

COMMENT ON COLUMN messages.admin_removed_at IS 'Set by administrative removal; independent of the sender-owned is_deleted/deleted_at pair. Content is preserved so a restore can return the message.';

COMMENT ON TABLE suggestion_dismissals IS 'Permanent per-viewer suppression of one account from people-you-may-know. Never a block: it changes no other surface.';

COMMENT ON COLUMN support_tickets.user_id IS 'Nullable: the public form produces a ticket before any account is resolved, and ON DELETE SET NULL keeps the ticket after a hard delete. contact_email is the durable channel.';

COMMENT ON COLUMN support_tickets.contact_email IS 'Where the response goes. Captured even for an authenticated ticket, because the account may be banned and this address is then the only channel that reaches the person.';

COMMENT ON COLUMN support_tickets.admin_action_id IS 'The audit row this ticket appeals against, populated when the ticket arrived through a signed link. Also the input to the conflict-of-interest rule: the staff member who wrote that row may not act on this ticket.';

COMMENT ON COLUMN support_tickets.assigned_to IS 'Set by a guarded update whose predicate re-checks that the ticket is still unassigned, so a second claimer is refused rather than silently overwriting the first.';

COMMENT ON COLUMN support_tickets.internal_note IS 'Staff-only. Never rendered into any user-facing response and never carried into any mail. staff_response is the field that reaches the user.';

COMMENT ON TABLE user_hashtag_affinity IS 'Per-user hashtag interest scores derived from user_events joined to post_hashtags over a bounded window. Rebuildable: truncating it costs only the next scheduled recompute.';

COMMENT ON COLUMN user_hashtag_affinity.score IS 'Normalised share of the user total, in [0,1]; comparable across users of different activity volumes.';

COMMENT ON COLUMN user_settings.email_opt_out IS 'Suppresses campaign mail only. Auth mail and moderation mail ignore it entirely: a password reset and a ban notice are not marketing and are not opt-out-able.';

COMMENT ON COLUMN user_settings.unsubscribe_token IS 'SHA-256 hex of the per-user unsubscribe secret. Null until first needed; the send path generates one lazily. Verified without a session, because the recipient following the link from a mail client has none.';

COMMENT ON COLUMN user_settings.suggestible IS 'False when the account has asked not to be offered in other people''s suggestions. Applied at read time, not only in the precompute job.';

COMMENT ON TABLE user_suggestions IS 'Precomputed people-you-may-know candidates. Rebuildable from source at any time. Every exclusion rule is re-applied at read time, because a twelve-hour cycle would otherwise keep suggesting an account the viewer followed this morning.';

COMMENT ON COLUMN user_verifications.revocation_actor IS 'moderator when a person decided, system when an account status change swept the badge away. A status-driven revocation is not a verdict and must not read as one.';

COMMENT ON COLUMN verification_categories.covers IS 'The occupations this category is meant to cover, shown to the requester so they can pick without guessing. Never parsed.';

COMMENT ON TABLE verification_requests IS 'The structured half of a verification_request support ticket. Immutable after insert: it records what was asked for, and the ticket beside it records what happened next.';

-- ============================================================
-- NOTES CARRIED FORWARD
-- ============================================================

-- Commentary from the previous revision of this file that the regeneration could not
-- place, because the table, column, index or routine it sat above no longer exists
-- under that name. It is kept here rather than dropped; delete a note once it has
-- been confirmed obsolete, and move it back inline if its anchor returns.

-- Note: email verification tokens and password reset tokens are stored in Redis
-- (see TokenServiceImpl), not in the relational database.
--
-- Declared before the modules that reference it. user_warnings.reason_key carries a foreign
-- key to report_reason_configs, so this block has to precede it: with the metadata module
-- further down the file, applying this schema top to bottom failed on that reference.
--
-- Monthly partitions for user_events
-- Tip: use pg_partman extension to auto-create future partitions in production
--
-- V28 opened a rolling window past the original 2026-06 ceiling; UserEventsPartitionJob keeps it
-- advancing (creates the partition two months ahead each month).
--
-- The one-open-ticket invariant. Partial and unique: terminal statuses are excluded so an answered
-- ticket does not stop the account opening another, and pending_confirmation is excluded so an
-- unconfirmed public submission cannot block the account's genuine ticket. The user_id IS NOT NULL
-- clause is required as well as implied, because NULL never equals NULL and the public form writes
-- rows with no user.
